name = "biggerthancali"
main = "src/index.ts"
compatibility_date = "2024-12-01"

routes = [
  { pattern = "biggerthancali.org", custom_domain = true },
  { pattern = "smallerthancali.org", custom_domain = true }
]
